### ISSUE TITLE
IndexError: cannot fit 'long' into an index-sized integer

### ISSUE THREAD

**Issue by ggrieco-tob** [trailofbits/manticore#541] opened 2017-10-27 22:01 UTC
### OS / Environment
ArchLinux

### Manticore version

baf2d769a624306f91fcca44bcff0b087f1bba69

### Python version

2.7

### Summary of the problem

IndexError: cannot fit 'long' into an index-sized integer

### Step to reproduce the behavior

I'm using [this script](https://gist.github.com/ggrieco-tob/3f3491956197e8ba19f88694af803bab) to test manticore.

$ ./evm.py [QuickFuzz.78967239524.88.5513551461481047294.38.evm.txt](https://github.com/trailofbits/manticore/files/1423565/QuickFuzz.78967239524.88.5513551461481047294.38.evm.txt)

### Expected behavior

It shouldn't crash.

### Actual behavior

Traceback (most recent call last):
  File "./evm.py", line 27, in <module>
    evm.execute() 
  File "/home/g/.local/lib/python2.7/site-packages/manticore-0.1.5-py2.7.egg/manticore/platforms/evm.py", line 841, in execute
    result = implementation(*arguments)
  File "/home/g/.local/lib/python2.7/site-packages/manticore-0.1.5-py2.7.egg/manticore/platforms/evm.py", line 1109, in CALLDATACOPY
    c = Operators.ITEBV(8,data_offset+i < len(self.data), Operators.ORD(self.data[data_offset+i]), 0)
IndexError: cannot fit 'long' into an index-sized integer

**Comment by mossberg** [comment] 2018-04-10 22:04
When I ran this, the `data_offset` operand to CALLDATACOPY was 22244935829384504656515512402634733411489739914894706861305669875436825346048, which I thought was suspiciously large, and perhaps indicative of an emulation error, but I confirmed that this is actually correct.

**Comment by mossberg** [comment] 2018-08-09 21:59
From the original issue, the exception was raised when executing the CALLDATACOPY instruction. I've ported the script to run on a recent master commit, 57107169689f62e4e331a85aa60502134079d20a, and get the following below. Since it 1) now makes it past the CALLDATACOPY instruction (and there is only 1 CALLDATACOPY in the bytecode) and 2) is unclear what this code should actually do in the first place and 3) this script is very old, I think it makes sense to close this now.



```
[I] (py3) vagrant ubuntu-bionic /v/m/541 ❯ py evm.py QuickFuzz.78967239524.88.5513551461481047294.38.evm.txt
PUSH1 0x60
PUSH1 0x40
MSTORE
PUSH1 0x40
PUSH1 0x40
MLOAD
SWAP1
DUP2
ADD
PUSH1 0x40
MSTORE
DUP1
PUSH1 0x3
DUP2
MSTORE
PUSH1 0x20
ADD
PUSH32 0x312e300000000000000000000000000000000000000000000000000000000000
DUP2
CALLDATACOPY
POP
PUSH1 0x4
Traceback (most recent call last):
  File "evm.py", line 32, in <module>
    evm.execute()
  File "/vagrant/manticore/manticore/platforms/evm.py", line 652, in execute
    arguments = self._pop_arguments()
  File "/vagrant/manticore/manticore/platforms/evm.py", line 594, in _pop_arguments
    arguments.append(self._pop())
  File "/vagrant/manticore/manticore/platforms/evm.py", line 545, in _pop
    raise StackUnderflow()
manticore.platforms.evm.StackUnderflow
```

```
#!/usr/bin/env python

from sys import argv
from manticore.core.smtlib.constraints import ConstraintSet
from manticore.platforms.evm import *
from manticore.ethereum import *

bytecode = open(argv[1], 'rb').read()

address=0x414141414141
origin=0x424242424242
price=1
data='AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
sender=0x434343434343
value=1
header={ 'coinbase': 0, 'timestamp': 0,
         'number': 0, 'difficulty': 0, 'gaslimit': 0,}
depth=0
gas=1000000

constraints = ConstraintSet()
world = EVMWorld(constraints)

from manticore import Manticore
Manticore.verbosity(3)

#evm = EVM(constraints, address, origin, price, data, sender, value, bytecode, header,  gas=gas, global_storage=world.storage )
# evm = EVM(constraints, address, origin, price, data, sender, value, bytecode, header,  gas=gas)
evm = EVM(constraints, address, data, origin, value, bytecode, world, gas)  # updated to master

while True:
    evm.execute()
```

**Closed by mossberg** 2018-08-09 21:59 UTC
Labels: bug, ethereum, needs_review
