### ISSUE TITLE
Manticore regression executing a simple contract

### ISSUE THREAD

**Issue by ggrieco-tob** [trailofbits/manticore#912] opened 2018-06-01 13:23 UTC
### OS / Environment

Distributor ID:	ArchLinux
Description:	ArchLinux
Release:	rolling-release

### Manticore version

Last revision (058943763b6aa44ee834538b60593667cf4f1070) fails but it used to work (e.g. 4a98110f4a74916305231a0a2fabc076e6218462)

### Python version

Python 2.7.14

### Summary of the problem

Manticore fails to concretely execute a contract.

### Step to reproduce the behavior

This is a small python contract to reproduce this issue:

```python
from manticore.ethereum import ManticoreEVM

m = ManticoreEVM(workspace_url="bug")
m.verbosity(3)
owner_account = m.create_account(balance=1000)

c = '''
contract C1 { 
  function f() returns (uint) {
    return 1;
  }
}

contract C2 { 
  address c;
  function C2(address x) {
    c = x;
  }
  function f() returns (uint) {
    return C1(c).f();
  }
}
'''

c1 = m.solidity_create_contract(c, owner=owner_account, contract_name='C1')
c2 = m.solidity_create_contract(c, owner=owner_account, contract_name='C2', args=[c1.address])
c2.f();
c2.f();
```

You can trigger this issue executing:

```
$ rm -Rf bug ; python bug.py                                               
```

### Expected behavior

It should run the script without failing.

### Actual behavior

```
2018-06-01 10:07:42,801: [32435] m.c.executor:INFO: load state 0
2018-06-01 10:07:42,816: [32435] m.c.plugin:INFO: Instructions executed: 17
2018-06-01 10:07:42,816: [32435] m.c.plugin:INFO: Coverage: 17 different instructions executed
2018-06-01 10:07:42,842: [32435] m.c.executor:INFO: load state 2
2018-06-01 10:07:42,881: [32435] m.c.plugin:INFO: Instructions executed: 101
2018-06-01 10:07:42,882: [32435] m.c.plugin:INFO: Coverage: 72 different instructions executed
2018-06-01 10:07:42,883: [32435] m.c.executor:INFO: load state 4
2018-06-01 10:07:42,939: [32435] m.c.plugin:INFO: Instructions executed: 332
2018-06-01 10:07:42,939: [32435] m.c.plugin:INFO: Coverage: 160 different instructions executed
Traceback (most recent call last):
  File "bug.py", line 31, in <module>
    c2.f();
  File "/home/g/.local/lib/python2.7/site-packages/manticore/ethereum.py", line 584, in f
    data=tx_data
  File "/home/g/.local/lib/python2.7/site-packages/manticore/ethereum.py", line 1008, in transaction
    raise NoAliveStates
manticore.ethereum.NoAliveStates
```

The immediate cause of this issue is that the first call to `c2.f();` throws when it should return a value.

**Comment by feliam** [comment] 2018-06-01 15:14
I did not try to reproduce it on the exact commit. But that works on my working copy so the solution is in the queue. 
Also some functionality changed. Now all testcases generation is delayed until you explicitly call m.finalize() at the end of your analysis. You may choose not to generate a report for all you states and do something like this instead
```
for state in m.all_states:
      #do stuff on state
```

**Comment by ggrieco-tob** [comment] 2018-06-04 20:20
The current revision of manticore (1fcb249ac76aeedf2b9f90d213ecbb6976d9b8fd) without any failure. However, checking the resulting alive state (you need to add `m.finalize()` to see it) reveals that manticore returns an unexpected value the second time `f()` is called.:

```
...
Transactions Nr. 4
Type: CALL
From: 0x67518339e369ab3d591d3569ab0a0d83b2ff5198
To: 0x1bfa530d5d685155e98cd7d9dd23f7b6a801cfef
Value: 0
Data: 26121ff0 (*)
Return_data: 0000000000000000000000000000000000000000000000000000000000000001 (*)

Function call:
f() -> RETURN
return: 1L


Transactions Nr. 5
Type: CALL
From: 0xd30a286ec6737b8b2a6a7b5fbb5d75b895f62956
To: 0x67518339e369ab3d591d3569ab0a0d83b2ff5198
Value: 0
Data: 26121ff0
Return_data: 26121ff000000000000000000000000000000000000000000000000000000000 (*)

Function call:
f() -> RETURN
return: 17219911917854084299749778639755835327755045716242581057573779540915269926912L
```

Last call to f should return 1, but instead it returns 17219911917854084299749778639755835327755045716242581057573779540915269926912.

**Comment by ggrieco-tob** [comment] 2018-06-05 18:11
I just tested this script with the last revision and this is the result:

```
...
Transactions Nr. 2
Type: CALL
From: 0x67518339e369ab3d591d3569ab0a0d83b2ff5198 
To: 0x1bfa530d5d685155e98cd7d9dd23f7b6a801cfef 
Value: 0 
Data: 00000000 (*)
Return_data: 0000000000000000000000000000000000000000000000000000000000000001 (*)

Function call:
{fallback}() -> RETURN 
return: () 


Transactions Nr. 3
Type: CALL
From: 0xd30a286ec6737b8b2a6a7b5fbb5d75b895f62956 
To: 0x67518339e369ab3d591d3569ab0a0d83b2ff5198 
Value: 0 
Data: 26121ff0 
Return_data: 0000000000000000000000000000000000000000000000000000000000000001 (*)

Function call:
f() -> RETURN 
return: 1L 


Transactions Nr. 4
Type: CALL
From: 0x67518339e369ab3d591d3569ab0a0d83b2ff5198 
To: 0x1bfa530d5d685155e98cd7d9dd23f7b6a801cfef 
Value: 0 
Data: 00000000 (*)
Return_data: 0000000000000000000000000000000000000000000000000000000000000001 (*)

Function call:
{fallback}() -> RETURN 
return: () 


Transactions Nr. 5
Type: CALL
From: 0xd30a286ec6737b8b2a6a7b5fbb5d75b895f62956 
To: 0x67518339e369ab3d591d3569ab0a0d83b2ff5198 
Value: 0 
Data: 26121ff0 
Return_data: 0000000000000000000000000000000000000000000000000000000000000001 (*)

Function call:
f() -> RETURN 
return: 1L 
```

Is it expected to see these "extra" transactions calling the fallback function?

**Comment by mossberg** [comment] 2018-06-11 20:52
Spent some time debugging this today. Those extra fallback transaction are errors! My current theory is that the internal transaction to C1 is being added to the EVMWorld._transactions list which should only contain external transactions. This happens because EVMWorld.execute calls _close_transaction any time an EndTx is raised. _close_transaction unconditionally adds a tx to the _transactions list

I think there could be a separate issue: why is data being send in tx 2 symbolic (all zeros)?

**Comment by feliam** [comment] 2018-06-11 20:55
EVMWorld._transactions should contain all tx. I think even TXERROR txs. 
You'll have world.transactions, world.human_transactions et.al to browse the appropiate set afterwards.
https://github.com/trailofbits/manticore/blob/master/manticore/platforms/evm.py#L2260-L2289

**Comment by mossberg** [comment] 2018-06-11 20:57
Ok, in that case, the internal transactions should appear in the .tx file, so it is correct to the see the "extra" transactions above, however I do not think they should be calling the _fallback_ function

**Comment by mossberg** [comment] 2018-06-11 21:02
On second thought, does it really make sense to have internal transactions in the tx file? I think the intention of that file is to contain the inputs you need to provide to the contract to get it into that state. So given this, maybe it should just be human transactions.

**Comment by feliam** [comment] 2018-06-11 21:06
Yes! .tx should have human_transactions only.  Not sure where or if we should export internal txs automatically. Need a script to extract stuff from the .pkl. or tutorial.

**Comment by mossberg** [comment] 2018-06-11 21:21
imo, let's not export internal tx automatically. not too hard to load the pkl and start inspecting yourself if someone really wants to.

**Comment by mossberg** [comment] 2018-07-05 17:16
Revisiting this. To close this issue we should do two things:

- (easy) modify the ethereum testcase generation code (ManticoreEVM._generate_testcase_callback) to not export internal tx. i looks like this line should use `.human_transactions` instead of `.transactions` https://github.com/trailofbits/manticore/blob/61270a2bda980f79280a44407aa57b9da16f8e7d/manticore/ethereum.py#L2099
- (less easy) we need to debug why the _fallback_ function is being called in this transaction trace. (https://github.com/trailofbits/manticore/issues/912#issuecomment-394807540, https://github.com/trailofbits/manticore/issues/912#issuecomment-396384809). from the time i spent debugging it appears this is because symbolic tx data is being concretized to all 0's for some reason. cc @feliam, if you have some time, maybe you can look at this

**Comment by mossberg** [comment] 2018-07-11 00:36
so i've tracked the "less easy" bug here down a bit.

if this line is commented out, the buggy behavior disappears (internal transaction data is not set to completely unconstrained (all zeros when concretized)).  https://github.com/trailofbits/manticore/issues/912#issuecomment-402793049

what is stumping me is why a call to EVM.write_buffer is somehow modifying EVMWorld._transactions[-1]. but in general i think there is some kind of problem with how we pass arguments to CALL.pos after the internal TX returns. that's where i stop understanding how the code works, from what I can see CALL.pos will have arguments that are popped from the stack, but I'm not sure the RETURN instruction, or code after it pushed things on the stack for CALL.pos to receive?

**Comment by feliam** [comment] 2018-07-11 02:32
Quick random  thoughts..
* CALL.pos must write the contents of the tx.return_data into memory.
* EVMWorld._transactions[-1] may change over time. As when a new tx is appended to it. double check you are referring to the same tx 
* Where CALL.pos get the arguments from?
So when CALL.pre is called it ends with a StartTx exception with triggers some special behavior. It simply re-pushes the arguments in the stack. (maybe this should be done in the @transac decorator btw)
https://github.com/trailofbits/manticore/blob/yolo_master/manticore/platforms/evm.py#L1343-L1347

**Comment by feliam** [comment] 2018-07-11 03:12
ArrayProxy is like a python list. You can have a number of references to the same object. And changing one reference changes all. 
read_buffer is wrong in this aspect as it may be returning a ... slice reference. A mess.
```

**Comment by mossberg** [comment] 2018-07-11 16:48
oops i posted the wrong link above. by "this line" i mean: https://github.com/trailofbits/manticore/blob/84b5bd8ba22d7303e6d082f105af3bd4efad7ddc/manticore/platforms/evm.py#L1919

**Comment by mossberg** [comment] 2018-07-11 18:11
since both #971 and #972 have been merged into yolo_master, I think we can effectively call this issue resolved. thank you very much @ggrieco-tob, and sorry for the delay!

**Closed by mossberg** 2018-07-11 18:11 UTC
Labels: ethereum, help wanted, priority-high
