### ISSUE TITLE
ManticoreEVM#create_account doc string error

### ISSUE THREAD

**Issue by dwhjames** [trailofbits/manticore#853] opened 2018-04-03 19:20 UTC
https://github.com/trailofbits/manticore/blob/bda9c091b58acf3ea19de876a75cd0e49e1ec5ea/manticore/ethereum.py#L868-L876

The doc string says this returns,

> :return: an EVMAccount

however, this actually returns a `long`.

It delegates to `EVMWorld#create_account`, which delegates to `EVMWorld#new_address`, which generates a random 160bit number.

It’s only `ManticoreEVM#create_contract` that returns an `EVMAccount`.

Should `create_account` return an `EVMAccount`? Or are longs the intended way to represent regular accounts?

**Comment by mossberg** [comment] 2018-04-03 19:55
thanks a lot @dwhjames :) , this is somewhat of a duplicate of #612, so i'm going to close this. yes, `create_account` current returns a long, which is how we represent regular accounts. the question of whether it _should_ is up to debate in #612, as far as i can see, there is not a compelling reason to change at the moment.

**Closed by mossberg** 2018-04-03 19:55 UTC

**Comment by dwhjames** [comment] 2018-04-03 20:42
Ah, I should have searched first.
Thanks for deduping.
