### ISSUE TITLE
unsupported operand type for long(): 'BitVecSub'

### ISSUE THREAD

**Issue by bannsec** [trailofbits/manticore#393] opened 2017-07-17 00:07 UTC
### OS / Environment
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 17.04
Release:        17.04
Codename:       zesty
```

### Python version
```
Python 2.7.12 (aff251e54385, Nov 09 2016, 18:02:49)
[PyPy 5.6.0 with GCC 4.8.2]
```

### Dependencies
```
backports.shutil-get-terminal-size==1.0.0
capstone==3.0.5rc2
cffi==1.9.0
decorator==4.1.1
enum34==1.1.6
greenlet==0.4.10
ipython==5.4.1
ipython-genutils==0.2.0
manticore==0.1.3
pathlib2==2.3.0
pexpect==4.2.1
pickleshare==0.7.4
pkg-resources==0.0.0
ply==3.10
prompt-toolkit==1.0.14
ptyprocess==0.5.2
pyelftools==0.24
Pygments==2.2.0
readline==6.2.4.1
scandir==1.5
simplegeneric==0.8.1
six==1.10.0
traitlets==4.3.2
unicorn==1.0.1
wcwidth==0.1.7
z3-solver==4.5.1.0.post2
```

### Summary of the problem
Playing with Manticore, I attempted to get it to solve a simple C binary of my own making, which was just the following:

```c
#include <stdio.h>
#include <string.h>
 
int main() {
    char buf[32];
 
    fgets(buf, 32, stdin);
 
    if (strstr(buf, "winner") == buf) {
        printf("Win!");
    }
 
    return 0;
}
```

I hook the winning `if` condition to print out the output, and the losing branch to drop states. However, I'm getting python Type errors after a while of execution:

```
2017-07-16 20:04:04,077: [88063] EXECUTOR:ERROR: Exception: unsupported operand type for long(): 'BitVecSub'
Traceback (most recent call last):
  File "/home/user/.virtualenvs/manticore/site-packages/manticore/core/executor.py", line 347, in run
    if not current_state.execute():
  File "/home/user/.virtualenvs/manticore/site-packages/manticore/core/state.py", line 123, in execute
    result = self.platform.execute()
  File "/home/user/.virtualenvs/manticore/site-packages/manticore/platforms/linux.py", line 1810, in execute
    self.syscall()
  File "/home/user/.virtualenvs/manticore/site-packages/manticore/platforms/linux.py", line 1655, in syscall
    return self._syscall_abi.invoke(implementation)
  File "/home/user/.virtualenvs/manticore/site-packages/manticore/core/cpu/abstractcpu.py", line 312, in invoke
    result = model(*argument_tuple)
  File "/home/user/.virtualenvs/manticore/site-packages/manticore/platforms/linux.py", line 1020, in sys_lseek
    signed_offset = ctypes.c_int64(offset).value
  File "/home/user/opt/mechaphish/pypy/pypy2-v5.6.0-linux64/lib_pypy/_ctypes/primitive.py", line 319, in __init__
    self.value = value
  File "/home/user/opt/mechaphish/pypy/pypy2-v5.6.0-linux64/lib_pypy/_ctypes/primitive.py", line 330, in _setvalue
    self._buffer[0] = value
TypeError: unsupported operand type for long(): 'BitVecSub'
```

Basically a bunch of those. I have not gotten it to finish execution.

### Step to reproduce the behavior
Run the attached test binary with the following commands:

```python
from manticore import Manticore
m = Manticore("./test")
@m.hook(0x400682)              
   ...: def win(state): 
   ...:     buf = state.cpu.read_bytes(state.cpu.RBP-0x30,0x20)
   ...:     res = ''.join(chr(state.solve_one(x)) for x in buf)
   ...:     print("Winning input is: " + res)
   ...:     m.terminate()
@m.hook(0x400691)              
   ...: def lose(state):
   ...:     state.abandon()
m.run(8)
```

### Expected behavior
Guessing manticore should be able to find the winning path?

### Actual behavior
Manticore seems to spin, chew up memory, and spit out Type errors.

**Comment by mossberg** [comment] 2018-09-20 20:33
sorry, but i think i will close this, since it's a little old, our issue log is starting to get distractingly big, and we likely won't have much time to look at this soon. however, if someone would like to help us debug this and understand the cause, that would be eligible for a bounty. bannsec, thanks a lot for reporting!

**Closed by mossberg** 2018-09-20 20:33 UTC
Labels: good first issue, help wanted
