### ISSUE TITLE
official docker echo error!

### ISSUE THREAD

**Issue by walterliang** [trailofbits/manticore#937] opened 2018-06-20 10:23 UTC
### OS / Environment

ubuntu16
### Summary of the problem
Traceback (most recent call last):
  File "/usr/local/bin/manticore", line 9, in <module>
    load_entry_point('manticore==0.1.9', 'console_scripts', 'manticore')()
  File "/usr/local/lib/python2.7/dist-packages/manticore/__main__.py", line 113, in main
    ethereum_cli(args)
  File "/usr/local/lib/python2.7/dist-packages/manticore/__main__.py", line 102, in ethereum_cli
    m.multi_tx_analysis(args.argv[0], args.contract, args.txlimit, not args.txnocoverage, args.txaccount)
  File "/usr/local/lib/python2.7/dist-packages/manticore/ethereum.py", line 1031, in multi_tx_analysis
    contract_account = self.solidity_create_contract(f, contract_name=contract_name, owner=owner_account)
  File "/usr/local/lib/python2.7/dist-packages/manticore/ethereum.py", line 928, in solidity_create_contract
    compile_results = self._compile(source_code, contract_name)
  File "/usr/local/lib/python2.7/dist-packages/manticore/ethereum.py", line 718, in _compile
    output, warnings = ManticoreEVM._run_solc(source_code)
  File "/usr/local/lib/python2.7/dist-packages/manticore/ethereum.py", line 675, in _run_solc
    **### raise Exception("Solidity compiler not installed.")
**Exception: Solidity compiler not installed.****

**Comment by mossberg** [comment] 2018-06-20 14:48
thanks for reporting, will look into this!

**Comment by mossberg** [comment] 2018-06-21 21:00
just looked into it. our dockerhub was configured so builds would automatically occur on updates to the master branch, however you need to opt into this with your docker pull command to select the master tag.

by default the docker pull command uses the `latest` docker tag, which for us had no automatic builds. I just set up automatic builds for tags in addition to the master branch. now, every time we tag manticore (do a release), there will be a new build, and a container for the latest release will automatically be build. we have a release planned very soon, so this should kick in :) i am going to close this for now, but please give it a try in a few days, and reopen this if the issue is still happening!

**Closed by mossberg** 2018-06-21 21:00 UTC

**Comment by JsHuang** [comment] 2018-07-26 03:56
Thanks.
