### ISSUE TITLE
Assertion failed: current_state is None

### ISSUE THREAD

**Issue by ggrieco-tob** [trailofbits/manticore#594] opened 2017-11-24 22:09 UTC
### OS / Environment

Distributor ID:	ArchLinux
Description:	ArchLinux
Release:	rolling-release

### Manticore version

Last revision (ce888766cd5a7947f250c0733d2429aac4587d8d)

### Python version

Python 2.7.13

### Summary of the problem

Assertion failed: current_state is None when manticore runs using a timeout.

### Step to reproduce the behavior

This issue is quite difficult to reproduce, I don't have a reliable way to do it. I suspect it is caused by a race condition because of the timeout. I don't know if it is relevant, but I'm using a single CPU to run manticore (procs = 1).

### Expected behavior

The assertion shouldn't fail.

### Actual behavior

```
....
  File "/home/gustavo/.local/lib/python2.7/site-packages/CEO-0.1-py2.7.egg/ceo/actions.py", line 180, in run
    m.run(procs=procs, timeout=timeout)
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.5-py2.7.egg/manticore/manticore.py", line 652, in run
    self._start_workers(procs, profiling=should_profile)
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.5-py2.7.egg/manticore/manticore.py", line 430, in _start_workers
    target()
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.5-py2.7.egg/manticore/core/executor.py", line 508, in run
    assert current_state is None
AssertionError
```

**Comment by mossberg** [comment] 2018-03-15 20:40
We notice this sometimes in our travis tests, but again, it's not easily reproducible.

**Comment by bradlarsen** [comment] 2020-05-26 16:35
This issue was never reliably reproduced, and was from 2017, using Python 2.  Closing!  If the issue is seen again using Python 3 in 2020, we can create a new issue.

**Closed by bradlarsen** 2020-05-26 16:35 UTC
Labels: needs_review
