### ISSUE TITLE
Automatically filling N for m.transactoin(data = m.sByte(N), ...)

### ISSUE THREAD

**Issue by ehildenb** [trailofbits/manticore#798] opened 2018-03-09 14:06 UTC
I've omitted information requested about my OS and such as this is a feature request (and not a bug report).

Consider the following python Manticore script: 

```python
#!/usr/bin/env python2

from manticore.ethereum import ManticoreEVM
from manticore.core.smtlib import Operators
from manticore.core.smtlib import solver

m = ManticoreEVM()

sol_contract='''
pragma solidity ^0.4.18;
contract UnprotectedWallet{
    address public owner;

    modifier onlyowner {
        require(msg.sender==owner);
        _;
    }

    function UnprotectedWallet() public {
        owner = msg.sender;
    }
    function changeOwner(address _newOwner) public {
       owner = _newOwner;
    }

    function deposit() payable public { }

    function withdraw() onlyowner public {
        msg.sender.transfer(this.balance);
    }
}
'''

creator_account  = m.create_account(balance=10**19)
attacker_account = m.create_account(balance=10**18)
contract_account = m.solidity_create_contract(sol_contract, owner=creator_account)

contract_account.deposit(creator_account, value=10**18)
m.transaction( caller  = attacker_account
             , address = contract_account
             , data    = m.SByte(36)
             , value   = m.SValue
             )
m.transaction( caller  = attacker_account
             , address = contract_account
             , data    = m.SByte(4)
             , value   = m.SValue
             )

for state in m.all_states:
    balance = state.platform.get_balance(attacker_account)
    state.constrain(balance > 10**18)
    if solver.check(state.constraints):
        print "Attack found!"
        m.generate_testcase(state, "Attack Found!")

print "Results are in %s" % m.workspace
m.finalize() # stop the exploration
```

For the two transactions I needed to specify `data = m.sByte(N)`, with `N` determined as 36 for the first TX and 4 for the second TX to explore the attack path.

It seems that users are asked to supply a value for `N` that is "large enough", when it would be easy enough for Manticore to look at the function signatures and determine the correct size `N` for each one (at least when you have the source available). Perhaps this could be added?

**Comment by mossberg** [comment] 2018-03-09 15:56
thanks @ehildenb, i think this is a great idea!

**Comment by ehildenb** [comment] 2018-03-11 15:39
Another thing you may think of (in addition to this feature request), is adding something like `m.SData`. Usage would be:

```
m.transaction(..., data = m.SData, ...)
```

Every time the VM queries for an entry in `m.SData` (eg. for the 3rd byte `m.SData[2]`), if it's the first time it generates a fresh `m.SByte`, if it's a subsequent time it uses the originally generated variable. The advantage of this approach is that you no longer need to have ABI compliant code to be able to infer the correct data-width to use for input (and thus you also don't need the Solidity source). Could think of it as a "lazy infinite list of `m.SByte`

I have no idea if this is feasible with how Manticore does execution currently, but it was a thought I had.

I think Josselin mentioned that you may be thinking about symbolic variable-length arrays, perhaps this could even just be implemented in terms of that.

**Comment by mossberg** [comment] 2018-03-14 17:27
I like that idea a lot, it's much more convenient than specifying a length of the data up front!

I can't quite say when we'll be able to get to these features; we're focusing most of our effort on correctness and functionality of analysis, and little less on higher level interface changes. We would absolutely love to see a PR for this though (and it would qualify for a bounty :)). Of course we are always here to provide guidance and answer questions for anyone thinking about starting :)

**Comment by ehildenb** [comment] 2018-03-17 16:03
I think I can try for a relatively simplistic version of this (where I find the max N needed given the contract automatically if the `data` field is not supplied). Two questions:

-   Is https://github.com/trailofbits/manticore/blob/fb79127bc2c6dafec0c1eea909eedf053a032ffe/manticore/ethereum.py#L535 the class I should be focused on? I also found a `transaction` function in `EVMWorld`, but did not also find a `solidity_create_contract` function there.
-   How would a bounty work?

**Comment by disconnect3d** [comment] 2019-01-15 19:47
The API has changed in the meantime and the `SValue`, `SByte` and `SData` are not a thing anymore.

The current API is:
* `m.make_symbolic_value()`
* `m.make_symbolic_arguments(...)`

I am not sure if the issue is still relevant, so I am closing it.

Regarding @ehildenb question about bounties: at the time I write this our wiki states 50-200$ payouts for bounties. We can probably make bigger payouts too. The amount ofc depends on case-by-case basis.

**Closed by disconnect3d** 2019-01-15 19:47 UTC
Labels: bounty, ethereum, help wanted, idea, question
