### ISSUE TITLE
Binaryninja and manticore don't play nice together

### ISSUE THREAD

**Issue by murmus** [trailofbits/manticore#199] opened 2017-04-27 14:59 UTC
### Summary of the problem
I should be able to import both binaryninja and manticore regardless of ordering. I'm not sure whose fault it is, but given that the traceback is from manticore, I figure that's a good place to start.

### Step to reproduce the behavior
```import binaryninja
import manticore```

Results in the following backtrace:

```Process SyncManager-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 249, in _bootstrap
    sys.stdin.close()
AttributeError: '_PythonScriptingInstanceInput' object has no attribute 'close'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/manticore/__init__.py", line 1, in <module>
    from .manticore import Manticore
  File "/usr/local/lib/python2.7/dist-packages/manticore/manticore.py", line 18, in <module>
    from .core.executor import Executor
  File "/usr/local/lib/python2.7/dist-packages/manticore/core/executor.py", line 32, in <module>
    manager.start(mgr_init)
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 528, in start
    self._address = reader.recv()
EOFError
```

```import manticore
import binaryninja```

Results in both being loaded.

### Expected behavior

Not a traceback.

**Comment by chronoslynx** [comment] 2017-04-27 15:42
`AttributeError: '_PythonScriptingInstanceInput' object has no attribute 'close'` That looks like multiprocessing is closing the [STDIN wrapper that binaryninja uses](https://github.com/Vector35/binaryninja-api/blob/dev/python/scriptingprovider.py#L643).

When I'm at a linux box I'll see if I can reproduce and debug

**Comment by murmus** [comment] 2017-04-27 15:52
Yep, shortly after I posted this, I noticed it was almost identical to the ipython stuff. I suspect it is the same issue, and on their end: https://github.com/Vector35/binaryninja-api/issues/392.

**Comment by douggard** [comment] 2017-05-03 17:46
This looks like a binaryninja issue. They overwrite `sys.std*`.

Commenting out lines 643 -645 in `binaryninja/python/binaryninja/scriptingprovider.py` got my code running.

```Python
PythonScriptingProvider().register()
# Wrap stdin/stdout/stderr for Python scripting provider implementation
original_stdin = sys.stdin
original_stdout = sys.stdout
original_stderr = sys.stderr

#sys.stdin = _PythonScriptingInstanceInput(sys.stdin)
#sys.stdout = _PythonScriptingInstanceOutput(sys.stdout, False)
#sys.stderr = _PythonScriptingInstanceOutput(sys.stderr, True)
```

**Comment by mossberg** [comment] 2017-08-29 19:10
It seems like that binary ninja issue has now been fixed, it would be great if someone could revisit this!

**Comment by psifertex** [comment] 2018-05-10 17:11
For reference, the previous change noted above wasn't actually a good fix (it broke some logging) and was reverted in our core. 

That said, we just implement a better fix for headless consoles. There may still be problems if manticore is loaded into the UI of BinaryNinja since that isn't a full terminal and the stdin/out hijacking still happens, but doing `import binaryninja` in a terminal no longer does that so this particular issue can probably be closed.

**Comment by mossberg** [comment] 2018-05-10 17:14
thx @psifertex, closing

**Closed by mossberg** 2018-05-10 17:14 UTC
Labels: bug, help wanted
