### ISSUE TITLE
ERROR: Exception: I/O operation on closed file

### ISSUE THREAD

**Issue by evanpjensen** [trailofbits/manticore#986] opened 2018-07-24 16:46 UTC
### OS / Environment
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04 LTS
Release:	18.04
Codename:	bionic

### Manticore version
61270a2bda980f79280a44407aa57b9da16f8e7d

### Python version
Python 2.7.15rc1

### Summary of the problem
When performing analysis of ELF 64-bit LSB shared object on Linux manticore errors with an `I/O operation on closed file` exception.

### Step to reproduce the behavior
run `manticore a.out` with the following program.
[return0.zip](https://github.com/trailofbits/manticore/files/2224564/return0.zip)

### Expected behavior
No crash

### Actual behavior
Crash

### Any relevant logs
```
xxxx@ubuntu:~/c/return0$ manticore a.out 
2018-07-24 12:47:27,895: [11773] m.manticore:INFO: Loading program a.out
2018-07-24 12:48:18,840: [11773] m.c.executor:ERROR: Exception: I/O operation on closed file
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.10-py2.7.egg/manticore/core/executor.py", line 483, in run
    self.generate_testcase(current_state, str(e))
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.10-py2.7.egg/manticore/core/executor.py", line 355, in generate_testcase
    self._publish('will_generate_testcase', state, 'test', message)
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.10-py2.7.egg/manticore/utils/event.py", line 118, in _publish
    self._publish_impl(_name, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.10-py2.7.egg/manticore/utils/event.py", line 134, in _publish_impl
    sink._publish_impl(_name, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.10-py2.7.egg/manticore/utils/event.py", line 126, in _publish_impl
    callback(robj(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.10-py2.7.egg/manticore/manticore.py", line 570, in _generate_testcase_callback
    testcase_id = self._output.save_testcase(state, name, message)
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.10-py2.7.egg/manticore/core/workspace.py", line 521, in save_testcase
    self._store.save_state(state, self._named_key('pkl'))
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.10-py2.7.egg/manticore/core/workspace.py", line 155, in save_state
    self._serializer.serialize(state, f)
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.10-py2.7.egg/manticore/core/workspace.py", line 45, in serialize
    f.write(cPickle.dumps(state, 2))
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.10-py2.7.egg/manticore/platforms/linux.py", line 71, in __getstate__
    state['pos'] = self.tell()
  File "/usr/local/lib/python2.7/dist-packages/manticore-0.1.10-py2.7.egg/manticore/platforms/linux.py", line 101, in tell
    return self.file.tell(*args)
ValueError: I/O operation on closed file

2018-07-24 12:48:18,859: [11773] m.manticore:INFO: Results in /home/xxxx/c/return0/mcore_hJ_nNo
2018-07-24 12:48:18,859: [11773] m.manticore:INFO: Total time: 50.1429710388

```

**Comment by devtty1er** [comment] 2018-07-24 18:08
Duplicate of #954

**Comment by mossberg** [comment] 2018-07-24 20:54
right this is a dup, although we could have done a better job describing the error in #954 😓 going to close this now, but thanks evan

**Closed by mossberg** 2018-07-24 20:54 UTC
